### ISSUE TITLE
binary search implement might be wrong

### ISSUE THREAD

**Issue by kkc** [dreddsa5dies/algorithm#6]
### Issue and Steps to Reproduce
I think the implementation of binary search might be wrong
this line `mid := (low + high)` doesn't consider the overflow issue
 
### Additional Details
* Installed packages:

**Comment by dreddsa5dies** [comment]
Hello, thank you very much for your attention to my project.
For efficiency, Golang does not check for overflow. If overflow is unlikely, but possible, checking is appropriate. When the problem domain raises that slight possibility to a likelihood, using the big.Int operations would be a better route.
But in this case there is a description of the algorithm, and not a complete solution for using the product-server.
I sincerely wish you success and, I hope, my answer was useful to you.
